export const USER_SIGN_IN = 'USER/SIGN-IN';
export const INVENTORY_LAST_SOLD_ITEMS = 'INVENTORY/LAST_SOLD_ITEMS';
export const USER_GET_DATA = 'USER/GET_DATA';
export const USER_SET_TRADE_URL = 'USER/SET_TRADE_URL';
export const INVENTORY_GET_INVENTORY = 'INVENTORY/GET_INVENTORY';
export const INVENTORY_SELECT_ITEM = 'INVENTORY/SELECT_ITEM';
export const USER_CRETE_TRADE = 'USER/CREATE_TRADE';
export const USER_GET_ACTIVE_TRADE = 'USER/GET_ACTIVE_TRADE';
