name: Merge Action

on:
  pull_request:
    branches: [ dev ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - name: Install
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Format
        run: npm run prettier
      - name: Build
        run: npm run build
